/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 25 02:43:43 GMT 2025
 */

package Alison_bugs.EvosuiteBug8.org.apache.commons.math3.distribution;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.apache.commons.math3.distribution.DiscreteDistribution;
import org.apache.commons.math3.util.Pair;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DiscreteDistribution_ESTest extends DiscreteDistribution_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(1889);
      Double double0 = new Double(1889);
      Pair<Integer, Double> pair0 = new Pair<Integer, Double>(integer0, double0);
      List<Pair<Integer, Double>> list0 = List.of(pair0, pair0, pair0, pair0, pair0);
      DiscreteDistribution<Integer> discreteDistribution0 = new DiscreteDistribution<Integer>(list0);
      discreteDistribution0.reseedRandomGenerator(1889);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer(1889);
      Double double0 = new Double((-706.4116));
      Pair<Integer, Double> pair0 = new Pair<Integer, Double>(integer0, double0);
      List<Pair<Integer, Double>> list0 = List.of(pair0, pair0, pair0, pair0, pair0);
      DiscreteDistribution<Integer> discreteDistribution0 = null;
      try {
        discreteDistribution0 = new DiscreteDistribution<Integer>(list0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -706.412 is smaller than the minimum (0)
         //
         verifyException("org.apache.commons.math3.distribution.DiscreteDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(1889);
      Double double0 = new Double(1770.68);
      Pair<Integer, Double> pair0 = new Pair<Integer, Double>(integer0, double0);
      List<Pair<Integer, Double>> list0 = List.of(pair0, pair0, pair0, pair0, pair0);
      DiscreteDistribution<Integer> discreteDistribution0 = new DiscreteDistribution<Integer>(list0);
      double double1 = discreteDistribution0.probability(integer0);
      assertEquals(1.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer(1889);
      Double double0 = new Double(1770.68);
      Pair<Integer, Double> pair0 = new Pair<Integer, Double>(integer0, double0);
      List<Pair<Integer, Double>> list0 = List.of(pair0, pair0, pair0, pair0, pair0);
      DiscreteDistribution<Integer> discreteDistribution0 = new DiscreteDistribution<Integer>(list0);
      double double1 = discreteDistribution0.probability((Integer) null);
      assertEquals(0.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Double double0 = new Double(1172);
      Pair<Integer, Double> pair0 = new Pair<Integer, Double>((Integer) null, double0);
      List<Pair<Integer, Double>> list0 = List.of(pair0, pair0, pair0, pair0, pair0);
      DiscreteDistribution<Integer> discreteDistribution0 = new DiscreteDistribution<Integer>(list0);
      double double1 = discreteDistribution0.probability((Integer) null);
      assertEquals(1.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Integer integer0 = new Integer(1889);
      Double double0 = new Double(1889);
      Pair<Integer, Double> pair0 = new Pair<Integer, Double>(integer0, double0);
      List<Pair<Integer, Double>> list0 = List.of(pair0, pair0, pair0, pair0, pair0);
      DiscreteDistribution<Integer> discreteDistribution0 = new DiscreteDistribution<Integer>(list0);
      Integer integer1 = new Integer((-729));
      double double1 = discreteDistribution0.probability(integer1);
      assertEquals(0.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Integer integer0 = new Integer(1900);
      Double double0 = new Double(1900);
      Pair<Integer, Double> pair0 = new Pair<Integer, Double>(integer0, double0);
      List<Pair<Integer, Double>> list0 = List.of(pair0, pair0, pair0, pair0, pair0);
      DiscreteDistribution<Integer> discreteDistribution0 = new DiscreteDistribution<Integer>(list0);
      List<Pair<Integer, Double>> list1 = discreteDistribution0.getSamples();
      assertEquals(5, list1.size());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Integer integer0 = new Integer(1889);
      Double double0 = new Double(1770.68);
      Pair<Integer, Double> pair0 = new Pair<Integer, Double>(integer0, double0);
      List<Pair<Integer, Double>> list0 = List.of(pair0, pair0, pair0, pair0, pair0);
      DiscreteDistribution<Integer> discreteDistribution0 = new DiscreteDistribution<Integer>(list0);
      Integer[] integerArray0 = discreteDistribution0.sample(1889);
      assertEquals(1889, integerArray0.length);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Integer integer0 = new Integer(1889);
      Double double0 = new Double(1889);
      Pair<Integer, Double> pair0 = new Pair<Integer, Double>(integer0, double0);
      List<Pair<Integer, Double>> list0 = List.of(pair0, pair0, pair0, pair0, pair0);
      DiscreteDistribution<Integer> discreteDistribution0 = new DiscreteDistribution<Integer>(list0);
      try { 
        discreteDistribution0.sample((-665));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // number of samples (-665)
         //
         verifyException("org.apache.commons.math3.distribution.DiscreteDistribution", e);
      }
  }
}
